---
# Install dependencies for building linux on Debian

- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: linux

# apt-get build-dep does not capture all requirements
- name: Install Linux kernel build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - bison
      - flex
      - git
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - sed
      - libssl-dev
      - libelf-dev
      - liburcu-dev
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
      - ntfs-3g
      - mdadm
      - rpcbind
      - portmap
      - hwinfo
      - open-iscsi
      - python3-pip
      - zstd
      - libncurses-dev
      - b4
    state: present
  tags: linux
