---
- name: Install Linux kernel build dependencies for SUSE
  become: true
  become_method: ansible.builtin.sudo
  community.general.zypper:
    name:
      - bison
      - flex
      - git-core
      - gcc
      - make
      - gawk
      - bc
      - dump
      - sed
      - libopenssl-devel
      - libelf-devel
      - liburcu8
      - diffutils
      - net-tools
      - ncurses-devel
      - xfsprogs
      - e2fsprogs
      - btrfsprogs
      - ntfs-3g
      - mdadm
      - rpcbind
      - portmap
      - hwinfo
      - open-iscsi
    disable_recommends: false
