- name: Run update-grub
  become: true
  become_flags: 'su - -c'
  become_method: ansible.builtin.sudo
  ansible.builtin.command: "update-bootloader --refresh"
  register: grub_update
  changed_when: "grub_update.rc == 0"
  tags:
    - linux
    - manual-update-grub
    - console
